default: &default
  adapter: postgresql
  host: localhost
  #username: postgres
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fundo_development

test:
  <<: *default
  database: fundo_test

production:
  <<: *default
  database: fundo_production
  username: fundo
  password: <%= ENV['FUNDO_DATABASE_PASSWORD'] %>
